# Generated by Django 3.1 on 2023-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogouttime',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
